[package]
name = "pallet-proxy-genesis-companion"
authors = [ "PureStake" ]
description = "A simple pallet that expands pallet-proxy with a genesis configuration"
edition = "2021"
version = "0.1.0"

[dependencies]
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
pallet-proxy = { workspace = true, default-features = false }
parity-scale-codec = { version = "3.0.0", default-features = false }
scale-info = { version = "2.0", default-features = false, features = [ "derive" ] }
sp-runtime = { workspace = true, default-features = false }

[dev-dependencies]
serde = "1.0.124"

pallet-balances = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }

[features]
default = [ "std" ]
std = [
	"frame-support/std",
	"frame-system/std",
	"pallet-proxy/std",
	"scale-info/std",
	"sp-runtime/std",
]
try-runtime = [ "frame-support/try-runtime" ]
