[package]
name = "pallet-evm-precompile-relay-encoder"
authors = [ "PureStake" ]
description = "A Precompile to make relay staking calls encoding accessible to pallet-evm"
edition = "2021"
version = "0.1.0"

[dependencies]
log = "0.4"
num_enum = { version = "0.5.3", default-features = false }
rustc-hex = { version = "2.0.1", default-features = false }

# Moonbeam
precompile-utils = { path = "../utils", default-features = false }

# Substrate
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-staking = { workspace = true }
parity-scale-codec = { version = "3.0.0", default-features = false, features = [ "derive" ] }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }


# Frontier
fp-evm = { workspace = true }
pallet-evm = { workspace = true, features = [ "forbid-evm-reentrancy" ] }

# Cumulus
cumulus-primitives-core = { workspace = true }

[dev-dependencies]
derive_more = "0.99"
hex-literal = "0.3.3"
serde = "1.0.100"
sha3 = "0.9"

# Moonbeam
precompile-utils = { path = "../utils", features = [ "testing" ] }

# Substrate
pallet-balances = { workspace = true }
pallet-timestamp = { workspace = true }
scale-info = { version = "2.0", default-features = false, features = [ "derive" ] }
sp-io = { workspace = true }

# Cumulus
cumulus-pallet-parachain-system = { workspace = true }

[features]
default = [ "std" ]
std = [
	"cumulus-primitives-core/std",
	"fp-evm/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-evm/std",
	"pallet-staking/std",
	"parity-scale-codec/std",
	"parity-scale-codec/std",
	"precompile-utils/std",
	"sp-runtime/std",
	"sp-std/std",
]
