[package]
name = "moonbeam-runtime-common"
authors = [ "PureStake" ]
description = "Common code shared between runtimes"
edition = "2021"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
version = "0.8.0-dev"

[dependencies]
impl-trait-for-tuples = "0.2.1"
log = "0.4"

# Moonbeam
moonbeam-xcm-benchmarks = { path = "../../pallets/moonbeam-xcm-benchmarks", optional = true, default-features = false }
pallet-asset-manager = { path = "../../pallets/asset-manager", default-features = false }
pallet-author-mapping = { path = "../../pallets/author-mapping", default-features = false }
pallet-migrations = { path = "../../pallets/migrations", default-features = false }
pallet-parachain-staking = { path = "../../pallets/parachain-staking", default-features = false }
pallet-randomness = { path = "../../pallets/randomness", default-features = false }
pallet-xcm-transactor = { path = "../../pallets/xcm-transactor", default-features = false }

# Substrate
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-collective = { workspace = true }
pallet-democracy = { workspace = true }
pallet-preimage = { workspace = true }
pallet-scheduler = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# Frontier
pallet-base-fee = { workspace = true }
pallet-evm = { workspace = true, features = [ "forbid-evm-reentrancy" ] }

# Nimbus
pallet-author-inherent = { workspace = true }
pallet-author-slot-filter = { workspace = true }

# Polkadot
xcm = { workspace = true }

[features]
std = [
	"frame-support/std",
	"pallet-asset-manager/std",
	"pallet-author-inherent/std",
	"pallet-author-mapping/std",
	"pallet-base-fee/std",
	"pallet-evm/std",
	"pallet-migrations/std",
	"pallet-parachain-staking/std",
	"pallet-randomness/std",
	"pallet-scheduler/std",
	"pallet-xcm-transactor/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"pallet-migrations/try-runtime",
]
