[package]
name = "pallet-evm-precompile-crowdloan-rewards"
authors = [ "PureStake" ]
description = "A Precompile to make crowdloan rewards accessible to pallet-evm"
edition = "2021"
version = "0.6.0"

[dependencies]
log = "0.4"
num_enum = { version = "0.5.3", default-features = false }
rustc-hex = { version = "2.0.1", default-features = false }

# Moonbeam
pallet-crowdloan-rewards = { workspace = true }
precompile-utils = { path = "../utils", default-features = false }

# Substrate
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-core = { workspace = true }
sp-std = { workspace = true }

# Frontier
fp-evm = { workspace = true }
pallet-evm = { workspace = true, features = [ "forbid-evm-reentrancy" ] }

[dev-dependencies]
derive_more = "0.99"
serde = "1.0.100"
sha3 = "0.9"

# Moonbeam
precompile-utils = { path = "../utils", features = [ "testing" ] }

# Substrate
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [ "max-encoded-len" ] }
pallet-balances = { workspace = true }
pallet-scheduler = { workspace = true }
pallet-timestamp = { workspace = true }
scale-info = { version = "2.0", default-features = false, features = [ "derive" ] }
sp-io = { workspace = true }
sp-runtime = { workspace = true }

# Cumulus
cumulus-pallet-parachain-system = { workspace = true }
cumulus-primitives-core = { workspace = true }
cumulus-primitives-parachain-inherent = { workspace = true }
cumulus-test-relay-sproof-builder = { workspace = true }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-primitives-core/std",
	"cumulus-primitives-parachain-inherent/std",
	"cumulus-test-relay-sproof-builder/std",
	"fp-evm/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-crowdloan-rewards/std",
	"pallet-evm/std",
	"precompile-utils/std",
	"sp-core/std",
	"sp-std/std",
]
