[package]
name = "moonbase-runtime"
authors = [ "PureStake" ]
build = "build.rs"
description = "Moonbase Runtime"
edition = "2021"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
version = "0.8.4"

[dependencies]
hex-literal = { version = "0.3.4", optional = true }
log = "0.4"
rlp = { version = "0.5", optional = true, default-features = false }
serde = { version = "1.0.101", optional = true, default-features = false, features = [ "derive" ] }
sha3 = { version = "0.8", optional = true, default-features = false }
smallvec = "1.8.0"

# Moonbeam
account = { path = "../../primitives/account/", default-features = false }
moonbeam-core-primitives = { path = "../../core-primitives", default-features = false }
moonbeam-relay-encoder = { path = "../relay-encoder", default-features = false }
moonbeam-runtime-common = { path = "../common", default-features = false }
precompile-utils = { path = "../../precompiles/utils", default-features = false }
session-keys-primitives = { path = "../../primitives/session-keys", default-features = false }
xcm-primitives = { path = "../../primitives/xcm/", default-features = false }

# Moonbeam pallets
moonbeam-xcm-benchmarks = { path = "../../pallets/moonbeam-xcm-benchmarks", default-features = false }
pallet-asset-manager = { path = "../../pallets/asset-manager", default-features = false }
pallet-author-mapping = { path = "../../pallets/author-mapping", default-features = false }
pallet-crowdloan-rewards = { workspace = true, default-features = false }
pallet-ethereum-chain-id = { path = "../../pallets/ethereum-chain-id", default-features = false }
pallet-ethereum-xcm = { path = "../../pallets/ethereum-xcm", default-features = false }
pallet-maintenance-mode = { path = "../../pallets/maintenance-mode", default-features = false, features = [ "xcm-support" ] }
pallet-migrations = { path = "../../pallets/migrations", default-features = false }
pallet-moonbeam-orbiters = { path = "../../pallets/moonbeam-orbiters", default-features = false }
pallet-parachain-staking = { path = "../../pallets/parachain-staking", default-features = false }
pallet-proxy-genesis-companion = { path = "../../pallets/proxy-genesis-companion", default-features = false }
pallet-randomness = { path = "../../pallets/randomness", default-features = false }
pallet-xcm-transactor = { path = "../../pallets/xcm-transactor", default-features = false }

# Moonbeam precompiles
pallet-evm-precompile-author-mapping = { path = "../../precompiles/author-mapping", default-features = false }
pallet-evm-precompile-balances-erc20 = { path = "../../precompiles/balances-erc20", default-features = false }
pallet-evm-precompile-batch = { path = "../../precompiles/batch", default-features = false }
pallet-evm-precompile-call-permit = { path = "../../precompiles/call-permit", default-features = false }
pallet-evm-precompile-collective = { path = "../../precompiles/collective", default-features = false }
pallet-evm-precompile-crowdloan-rewards = { path = "../../precompiles/crowdloan-rewards", default-features = false }
pallet-evm-precompile-democracy = { path = "../../precompiles/pallet-democracy", default-features = false }
pallet-evm-precompile-parachain-staking = { path = "../../precompiles/parachain-staking", default-features = false }
pallet-evm-precompile-proxy = { path = "../../precompiles/proxy", default-features = false }
pallet-evm-precompile-randomness = { path = "../../precompiles/randomness", default-features = false }
pallet-evm-precompile-relay-encoder = { path = "../../precompiles/relay-encoder", default-features = false }
pallet-evm-precompile-xcm-transactor = { path = "../../precompiles/xcm-transactor", default-features = false }
pallet-evm-precompile-xcm-utils = { path = "../../precompiles/xcm-utils", default-features = false }
pallet-evm-precompile-xtokens = { path = "../../precompiles/xtokens", default-features = false }
pallet-evm-precompileset-assets-erc20 = { path = "../../precompiles/assets-erc20", default-features = false }

# Moonbeam tracing
evm-tracing-events = { path = "../../primitives/rpc/evm-tracing-events", optional = true, default-features = false }
moonbeam-evm-tracer = { path = "../evm_tracer", optional = true, default-features = false }
moonbeam-rpc-primitives-debug = { path = "../../primitives/rpc/debug", default-features = false }
moonbeam-rpc-primitives-txpool = { path = "../../primitives/rpc/txpool", default-features = false }

# Substrate
frame-executive = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
frame-system-rpc-runtime-api = { workspace = true, default-features = false }
pallet-assets = { workspace = true, default-features = false }
pallet-balances = { workspace = true, default-features = false }
pallet-collective = { workspace = true, default-features = false }
pallet-conviction-voting = { workspace = true, default-features = false }
pallet-democracy = { workspace = true, default-features = false }
pallet-identity = { workspace = true, default-features = false }
pallet-preimage = { workspace = true, default-features = false }
pallet-proxy = { workspace = true, default-features = false }
pallet-randomness-collective-flip = { workspace = true, default-features = false }
pallet-referenda = { workspace = true, default-features = false }
pallet-scheduler = { workspace = true, default-features = false }
pallet-society = { workspace = true, default-features = false }
pallet-sudo = { workspace = true, default-features = false }
pallet-timestamp = { workspace = true, default-features = false }
pallet-transaction-payment = { workspace = true, default-features = false }
pallet-transaction-payment-rpc-runtime-api = { workspace = true, default-features = false }
pallet-treasury = { workspace = true, default-features = false }
pallet-utility = { workspace = true, default-features = false }
pallet-whitelist = { workspace = true, default-features = false }
parity-scale-codec = { version = "3.0.0", default-features = false, features = [ "derive", "max-encoded-len" ] }
scale-info = { version = "2.0", default-features = false, features = [ "derive" ] }
sp-api = { workspace = true, default-features = false }
sp-block-builder = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-debug-derive = { workspace = true, default-features = false }
sp-inherents = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-offchain = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-session = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-transaction-pool = { workspace = true, default-features = false }
sp-version = { workspace = true, default-features = false }

# Frontier
fp-evm = { workspace = true, default-features = false }
fp-rpc = { workspace = true, default-features = false }
fp-self-contained = { workspace = true, default-features = false }
pallet-base-fee = { workspace = true, default-features = false }
pallet-ethereum = { workspace = true, default-features = false, features = [ "forbid-evm-reentrancy" ] }
pallet-evm = { workspace = true, default-features = false, features = [ "forbid-evm-reentrancy" ] }
pallet-evm-precompile-blake2 = { workspace = true, default-features = false }
pallet-evm-precompile-bn128 = { workspace = true, default-features = false }
pallet-evm-precompile-dispatch = { workspace = true, default-features = false }
pallet-evm-precompile-modexp = { workspace = true, default-features = false }
pallet-evm-precompile-sha3fips = { workspace = true, default-features = false }
pallet-evm-precompile-simple = { workspace = true, default-features = false }

# Cumulus / Nimbus
cumulus-pallet-dmp-queue = { workspace = true, default-features = false }
cumulus-pallet-parachain-system = { workspace = true, default-features = false }
cumulus-pallet-xcm = { workspace = true, default-features = false }
cumulus-pallet-xcmp-queue = { workspace = true, default-features = false }
cumulus-primitives-core = { workspace = true, default-features = false }
cumulus-primitives-timestamp = { workspace = true, default-features = false }
cumulus-primitives-utility = { workspace = true, default-features = false }
nimbus-primitives = { workspace = true, default-features = false }
pallet-author-inherent = { workspace = true, default-features = false }
pallet-author-slot-filter = { workspace = true, default-features = false }
parachain-info = { workspace = true, default-features = false }

# Polkadot / XCM
orml-traits = { workspace = true, default-features = false }
orml-xcm-support = { workspace = true, default-features = false }
orml-xtokens = { workspace = true, default-features = false }
pallet-xcm = { workspace = true, default-features = false }
pallet-xcm-benchmarks = { workspace = true, optional = true, default-features = false }
polkadot-core-primitives = { workspace = true, default-features = false }
polkadot-parachain = { workspace = true, default-features = false }
xcm = { workspace = true, default-features = false }
xcm-builder = { workspace = true, default-features = false }
xcm-executor = { workspace = true, default-features = false }

# Benchmarking
frame-benchmarking = { workspace = true, optional = true, default-features = false }
frame-system-benchmarking = { workspace = true, optional = true, default-features = false }
frame-try-runtime = { workspace = true, optional = true, default-features = false }

[dev-dependencies]
ethereum = { version = "0.14.0" }
hex = "0.4"
sha3 = "0.9"

cumulus-primitives-parachain-inherent = { workspace = true, default-features = false }
cumulus-test-relay-sproof-builder = { workspace = true, default-features = false }

polkadot-runtime-parachains = { workspace = true }
xcm-simulator = { workspace = true }

precompile-utils = { path = "../../precompiles/utils", default-features = false, features = [ "testing" ] }

[build-dependencies]
substrate-wasm-builder = { workspace = true }

[features]
default = [ "std" ]
std = [
	"account/std",
	"cumulus-pallet-dmp-queue/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-xcm/std",
	"cumulus-pallet-xcmp-queue/std",
	"cumulus-primitives-core/std",
	"cumulus-primitives-timestamp/std",
	"evm-tracing-events/std",
	"fp-evm/std",
	"fp-rpc/std",
	"fp-self-contained/std",
	"frame-benchmarking/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"moonbeam-core-primitives/std",
	"moonbeam-evm-tracer/std",
	"moonbeam-rpc-primitives-debug/std",
	"moonbeam-rpc-primitives-txpool/std",
	"moonbeam-runtime-common/std",
	"nimbus-primitives/std",
	"orml-xtokens/std",
	"pallet-asset-manager/std",
	"pallet-assets/std",
	"pallet-author-inherent/std",
	"pallet-author-mapping/std",
	"pallet-author-slot-filter/std",
	"pallet-balances/std",
	"pallet-base-fee/std",
	"pallet-collective/std",
	"pallet-conviction-voting/std",
	"pallet-crowdloan-rewards/std",
	"pallet-democracy/std",
	"pallet-ethereum-chain-id/std",
	"pallet-ethereum-xcm/std",
	"pallet-ethereum/std",
	"pallet-evm-precompile-author-mapping/std",
	"pallet-evm-precompile-balances-erc20/std",
	"pallet-evm-precompile-batch/std",
	"pallet-evm-precompile-call-permit/std",
	"pallet-evm-precompile-collective/std",
	"pallet-evm-precompile-democracy/std",
	"pallet-evm-precompile-parachain-staking/std",
	"pallet-evm-precompile-randomness/std",
	"pallet-evm-precompile-xcm-transactor/std",
	"pallet-evm-precompile-xcm-utils/std",
	"pallet-evm-precompile-xtokens/std",
	"pallet-evm-precompileset-assets-erc20/std",
	"pallet-evm/std",
	"pallet-identity/std",
	"pallet-maintenance-mode/std",
	"pallet-migrations/std",
	"pallet-moonbeam-orbiters/std",
	"pallet-parachain-staking/std",
	"pallet-preimage/std",
	"pallet-proxy-genesis-companion/std",
	"pallet-proxy/std",
	"pallet-randomness-collective-flip/std",
	"pallet-randomness/std",
	"pallet-referenda/std",
	"pallet-scheduler/std",
	"pallet-society/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-treasury/std",
	"pallet-utility/std",
	"pallet-whitelist/std",
	"pallet-xcm-transactor/std",
	"pallet-xcm/std",
	"parachain-info/std",
	"parity-scale-codec/std",
	"precompile-utils/std",
	"scale-info/std",
	"serde",
	"session-keys-primitives/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm-primitives/std",
	"xcm/std",
 ]

# Must be enabled for tracing runtimes only
evm-tracing = [ "evm-tracing-events", "moonbeam-evm-tracer", "rlp", "sha3" ]

# Allow to print logs details (no wasm:stripped)
force-debug = [ "sp-debug-derive/force-debug" ]

# Will be enabled by the `wasm-builder` when building the runtime for WASM.
runtime-wasm = []

# A feature that should be enabled when the runtime should be build for on-chain
# deployment. This will disable stuff that shouldn't be part of the on-chain wasm
# to make it smaller like logging for example.
on-chain-release-build = [ "sp-api/disable-logging" ]

runtime-benchmarks = [
	"cumulus-pallet-parachain-system/runtime-benchmarks",
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"hex-literal",
	"moonbeam-xcm-benchmarks/runtime-benchmarks",
	"pallet-asset-manager/runtime-benchmarks",
	"pallet-author-inherent/runtime-benchmarks",
	"pallet-author-mapping/runtime-benchmarks",
	"pallet-author-slot-filter/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"pallet-conviction-voting/runtime-benchmarks",
	"pallet-crowdloan-rewards/runtime-benchmarks",
	"pallet-ethereum-xcm/runtime-benchmarks",
	"pallet-ethereum/runtime-benchmarks",
	"pallet-migrations/runtime-benchmarks",
	"pallet-moonbeam-orbiters/runtime-benchmarks",
	"pallet-parachain-staking/runtime-benchmarks",
	"pallet-preimage/runtime-benchmarks",
	"pallet-randomness/runtime-benchmarks",
	"pallet-referenda/runtime-benchmarks",
	"pallet-society/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-xcm-benchmarks",
	"pallet-xcm-transactor/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"session-keys-primitives/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
]
try-runtime = [
	"frame-executive/try-runtime",
	"frame-system/try-runtime",
	"frame-try-runtime",
	"moonbeam-runtime-common/try-runtime",
	"pallet-asset-manager/try-runtime",
	"pallet-author-mapping/try-runtime",
	"pallet-author-slot-filter/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-collective/try-runtime",
	"pallet-conviction-voting/try-runtime",
	"pallet-democracy/try-runtime",
	"pallet-maintenance-mode/try-runtime",
	#"pallet-crowdloan-rewards/try-runtime",
	"pallet-maintenance-mode/try-runtime",
	"pallet-migrations/try-runtime",
	"pallet-parachain-staking/try-runtime",
	"pallet-preimage/try-runtime",
	"pallet-referenda/try-runtime",
	"pallet-scheduler/try-runtime",
	"pallet-society/try-runtime",
	"pallet-timestamp/try-runtime",
]

moonbase-runtime-benchmarks = []
