[package]
name = "session-keys-primitives"
authors = [ "PureStake" ]
description = "Primitives for session keys"
edition = "2021"
version = "0.1.0"

[dependencies]
async-trait = { version = "0.1", optional = true }
frame-support = { workspace = true }
nimbus-primitives = { workspace = true }
parity-scale-codec = { version = "3.0.0", default-features = false, features = [ "derive" ] }
scale-info = { version = "2.0", default-features = false, features = [ "derive" ] }
sp-api = { workspace = true }
sp-application-crypto = { workspace = true }
sp-consensus-babe = { workspace = true }
sp-consensus-vrf = { workspace = true }
sp-core = { workspace = true }
sp-inherents = { workspace = true }
sp-keystore = { workspace = true, optional = true, default-features = false }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

[features]
default = [ "std" ]
std = [
	"async-trait",
	"frame-support/std",
	"nimbus-primitives/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"sp-api/std",
	"sp-application-crypto/std",
	"sp-consensus-babe/std",
	"sp-consensus-vrf/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-keystore",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = []
