[package]
name = "pallet-evm-precompile-xcm-utils"
authors = [ "PureStake" ]
description = "A Precompile to make xcm utilities accessible to pallet-evm"
edition = "2021"
version = "0.1.0"

[dependencies]
num_enum = { version = "0.5.3", default-features = false }

# Moonbeam
precompile-utils = { path = "../utils", default-features = false }
xcm-primitives = { path = "../../primitives/xcm", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }

# Frontier
fp-evm = { workspace = true, default-features = false }
pallet-evm = { workspace = true, default-features = false, features = [ "forbid-evm-reentrancy" ] }

# Polkadot
xcm = { workspace = true, default-features = false }
xcm-executor = { workspace = true, default-features = false }

[dev-dependencies]
derive_more = "0.99"
serde = "1.0.100"
sha3 = "0.9"

# Moonbeam
precompile-utils = { path = "../utils", features = [ "testing" ] }

# Substrate
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [ "max-encoded-len" ] }
pallet-balances = { workspace = true }
pallet-timestamp = { workspace = true }
scale-info = { version = "2.0", default-features = false, features = [ "derive" ] }
sp-io = { workspace = true }
sp-runtime = { workspace = true }

# Cumulus
cumulus-primitives-core = { workspace = true }

# Polkadot
polkadot-parachain = { workspace = true }
xcm-builder = { workspace = true }

# ORML
orml-traits = { workspace = true }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"orml-traits/std",
	"pallet-balances/std",
	"pallet-evm/std",
	"pallet-timestamp/std",
	"polkadot-parachain/std",
	"precompile-utils/std",
	"sp-core/std",
	"sp-io/std",
	"sp-std/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm-primitives/std",
]
