[package]
name = "pallet-evm-precompile-author-mapping"
authors = [ "PureStake" ]
description = "A Precompile to make pallet-author-mapping accessible to pallet-evm"
edition = "2021"
version = "0.2.0"

[dependencies]
log = "0.4"
num_enum = { version = "0.5.3", default-features = false }

# Moonbeam
pallet-author-mapping = { path = "../../pallets/author-mapping", default-features = false }
precompile-utils = { path = "../utils", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }

# Frontier
fp-evm = { workspace = true, default-features = false }
pallet-evm = { workspace = true, default-features = false, features = [ "forbid-evm-reentrancy" ] }

# Nimbus
nimbus-primitives = { workspace = true, default-features = false }

[dev-dependencies]
derive_more = "0.99"
hex-literal = "0.3.4"
serde = "1.0.100"

# Moonbeam
pallet-author-mapping = { path = "../../pallets/author-mapping" }
precompile-utils = { path = "../utils", features = [ "testing" ] }

# Substrate
pallet-balances = { workspace = true }
pallet-scheduler = { workspace = true }
pallet-timestamp = { workspace = true }
scale-info = { version = "2.0", default-features = false, features = [ "derive" ] }
sp-runtime = { workspace = true }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"fp-evm/std",
	"frame-support/std",
	"frame-system/std",
	"nimbus-primitives/std",
	"pallet-author-mapping/std",
	"pallet-evm/std",
	"precompile-utils/std",
	"sp-core/std",
	"sp-io/std",
	"sp-std/std",
]
