[package]
name = "moonbeam-check-rpc"
authors = { workspace = true }
edition = "2021"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
repository = { workspace = true }
version = "0.6.0"

[dependencies]
futures = { workspace = true }
jsonrpsee = { workspace = true, features = [ "macros", "server" ] }
serde = { workspace = true, features = [ "derive" ] }
sha3 = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, features = [ "sync", "time" ] }

# Moonbeam
moonbeam-core-primitives = { workspace = true, features = [ "std" ] }

# Substrate
frame-system = { workspace = true }
frame-support = { workspace = true }
sc-rpc-api = { workspace = true }
sc-client-api = { workspace = true }
sc-network = { workspace = true }
sc-service = { workspace = true }
sc-utils = { workspace = true }
sp-block-builder = { workspace = true }
sp-blockchain = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-rpc = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
sp-transaction-pool = { workspace = true }