[package]
name = "manual-xcm-rpc"
authors = [ "PureStake" ]
edition = "2021"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
repository = "https://github.com/PureStake/moonbeam/"
version = "0.1.0"

[dependencies]
flume = "0.10.9"
hex-literal = "0.3.3"
jsonrpsee = { version = "0.15.0", default-features = false, features = [ "macros", "server" ] }
parity-scale-codec = "3.0.0"
xcm = { git = "https://github.com/purestake/polkadot", branch = "moonbeam-polkadot-v0.9.32", default-features = false }

cumulus-primitives-core = { git = "https://github.com/purestake/cumulus", branch = "moonbeam-polkadot-v0.9.32" }
