[package]
name = "moonbeam-cli"
authors = [ "PureStake" ]
edition = "2021"
version = "0.28.0"
[dependencies]
clap = { version = "4.0.9", features = [ "derive" ] }
log = "0.4.8"
parity-scale-codec = "3.0.0"

# Moonbeam
cli-opt = { package = "moonbeam-cli-opt", path = "../cli-opt", default-features = false }
service = { package = "moonbeam-service", path = "../service", default-features = false }

# Substrate
frame-benchmarking-cli = { workspace = true }
sc-cli = { workspace = true }
sc-finality-grandpa = { workspace = true }
sc-service = { workspace = true }
sc-sysinfo = { workspace = true }
sc-telemetry = { workspace = true }
sc-tracing = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
substrate-prometheus-endpoint = { workspace = true }
try-runtime-cli = { workspace = true, optional = true }

# Cumulus / Nimbus
cumulus-client-cli = { workspace = true }
cumulus-client-service = { workspace = true }
cumulus-primitives-core = { workspace = true }
nimbus-primitives = { workspace = true }

# Polkadot
polkadot-cli = { workspace = true }
polkadot-parachain = { workspace = true }
polkadot-primitives = { workspace = true }
polkadot-service = { workspace = true }

[build-dependencies]
substrate-build-script-utils = { workspace = true }

[features]
default = [ "moonbase-native", "moonbeam-native", "moonriver-native", "wasmtime", "westend-native" ]

westend-native = [ "polkadot-service/westend-native" ]

moonbase-native = [ "service/moonbase-native", "westend-native" ]
moonbeam-native = [ "service/moonbeam-native" ]
moonriver-native = [ "service/moonriver-native" ]

runtime-benchmarks = [ "polkadot-service/runtime-benchmarks", "service/runtime-benchmarks" ]
try-runtime = [
	"service/try-runtime",
	"try-runtime-cli",
]
wasmtime = [ "sc-cli/wasmtime" ]

moonbase-runtime-benchmarks = [ "service/moonbase-runtime-benchmarks" ]
