[package]
name = "pallet-randomness"
authors = [ "PureStake" ]
description = "Provides randomness"
edition = "2018"
version = "0.1.0"

[dependencies]
frame-benchmarking = { workspace = true, optional = true, default-features = false }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
hex = { version = "0.4.3", default-features = false }
log = "0.4"
nimbus-primitives = { workspace = true, default-features = false }
parity-scale-codec = { version = "3.0.0", default-features = false, features = [ "derive" ] }
scale-info = { version = "2.0", default-features = false, features = [ "derive" ] }
serde = { version = "1.0.101", optional = true }
session-keys-primitives = { path = "../../primitives/session-keys", default-features = false }
sp-consensus-vrf = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }

# Frontier
pallet-evm = { workspace = true, default-features = false, features = [ "forbid-evm-reentrancy" ] }

[dev-dependencies]
derive_more = "0.99"
pallet-author-mapping = { path = "../author-mapping" }
pallet-balances = { workspace = true }

[features]
default = [ "std" ]
std = [
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"hex/std",
	"nimbus-primitives/std",
	"pallet-evm/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"serde",
	"session-keys-primitives/std",
	"sp-consensus-vrf/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"session-keys-primitives/runtime-benchmarks",
]
# try-runtime = [ "frame-support/try-runtime" ]
