[package]
name = "pallet-maintenance-mode"
authors = [ "PureStake" ]
description = "Puts a FRAME-based runtime into maintenance mode where restricted interactions are allowed."
edition = "2021"
version = "0.1.0"

[dependencies]
log = "0.4"

# Substrate
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
parity-scale-codec = { version = "3.0.0", default-features = false }
scale-info = { version = "2.0", default-features = false, features = [ "derive" ] }
sp-runtime = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }

cumulus-primitives-core = { workspace = true, optional = true, default-features = false }

[dev-dependencies]
sp-core = { workspace = true }
sp-io = { workspace = true }

[features]
default = [ "std", "xcm-support" ]
std = [
	"cumulus-primitives-core/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-std/std",
]
try-runtime = [ "frame-support/try-runtime" ]
xcm-support = [ "cumulus-primitives-core" ]
