[package]
name = "moonbeam-relay-encoder"
authors = { workspace = true }
edition = "2021"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
repository = { workspace = true }
version = "0.1.0"

[dependencies]

# Moonbeam
pallet-evm-precompile-relay-encoder = { workspace = true }
xcm-primitives = { workspace = true }
pallet-xcm-transactor = { workspace = true }

# Substrate
frame-system = { workspace = true }
pallet-staking = { workspace = true }
parity-scale-codec = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
sp-io = { workspace = true }

# Cumulus
cumulus-primitives-core = { workspace = true }

# Polkadot
xcm = { workspace = true }

[dev-dependencies]
frame-support = { workspace = true, features = [ "std" ] }
pallet-proxy = { workspace = true, features = [ "std" ] }
pallet-utility = { workspace = true, features = [ "std" ] }

kusama-runtime = { workspace = true }
polkadot-runtime = { workspace = true }
polkadot-runtime-parachains = { workspace = true }
rococo-runtime = { workspace = true }
westend-runtime = { workspace = true }
moonriver-runtime = { workspace = true }
moonbase-runtime = { workspace = true }
moonbeam-runtime = { workspace = true }

[features]
default = [ "std" ]
std = [
	"cumulus-primitives-core/std",
	"frame-system/std",
	"pallet-evm-precompile-relay-encoder/std",
	"pallet-staking/std",
	"pallet-xcm-transactor/std",
	"parity-scale-codec/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-io/std",
	"xcm-primitives/std",
	"moonriver-runtime/std",
	"moonbeam-runtime/std",
	"moonbase-runtime/std",
]
