[package]
name = "moonbeam-relay-encoder"
authors = [ "PureStake" ]
edition = "2021"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
repository = "https://github.com/PureStake/moonbeam/"
version = "0.1.0"

[dependencies]

# Moonbeam
pallet-evm-precompile-relay-encoder = { path = "../../precompiles/relay-encoder/", default-features = false }
xcm-primitives = { path = "../../primitives/xcm", default-features = false }

# Substrate
frame-system = { workspace = true, default-features = false }
pallet-staking = { workspace = true, default-features = false }
parity-scale-codec = { version = "3.0.0", default-features = false, features = [ "derive" ] }
sp-runtime = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }

# Cumulus
cumulus-primitives-core = { workspace = true, default-features = false }

[dev-dependencies]
frame-support = { workspace = true }
pallet-proxy = { workspace = true }
pallet-utility = { workspace = true }

kusama-runtime = { workspace = true }
polkadot-runtime = { workspace = true }
rococo-runtime = { workspace = true }
westend-runtime = { workspace = true }

[features]
default = [ "std" ]
std = [
	"cumulus-primitives-core/std",
	"frame-system/std",
	"pallet-evm-precompile-relay-encoder/std",
	"pallet-staking/std",
	"parity-scale-codec/std",
	"parity-scale-codec/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm-primitives/std",
]
