name: Build

# Using a single file workflow is the preferred solution for our CI over workflow_runs.
# 1. It generates only 1 action item in the list making it more readable
# 2. It includes the PR/Commit text in the action item
# 3. Artifacts are not available between workflows.

on:
  pull_request:
  push:
    branches:
      - master
      - perm-*
  workflow_dispatch:
    inputs:
      pull_request:
        description: set to pull_request number to execute on external pr
        required: false

env:
  NODE_OPTIONS: "--max-old-space-size=12288"

jobs:
  ####### Check files and formatting #######
  set-tags:
    runs-on:
      labels: bare-metal
    strategy:
      matrix:
        chain: [1, 2, 3, 4, 5, 6]
    env:
      GH_WORKFLOW_MATRIX_CHAIN: ${{ matrix.chain }}
    steps:
      - name: Cleanup
        run: |
          for runtime in moonbase moonriver moonbeam; do
            if [[ -d runtime/$runtime/target ]]; then
              echo "Removing runtime/$runtime/target"
              ls -lna runtime/$runtime/target
              docker run -u 0 -v $(pwd)/runtime/$runtime/:/runtime \
                -it --entrypoint bash paritytech/srtool:1.69.0 -c "id; ls -lna /runtime/target; rm -rf /runtime/target"
            fi
          done
          sleep 120
