name: Check licenses

on:
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: ./.github/workflow-templates/rust-toolchain
      - name: Verify Licenses
        run: |
          cargo install cargo-license
          ./scripts/verify-licenses.sh
