[package]
name = "pallet-ethereum-xcm"
authors = [ "Parity Technologies <admin@parity.io>" ]
description = "Xcm Transact compatibility for pallet-etherum."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/paritytech/frontier/"
version = "1.0.0-dev"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
ethereum = { version = "0.14.0", default-features = false, features = [ "with-codec" ] }
serde = { version = "1.0.137", optional = true }

# Parity
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
ethereum-types = { version = "0.14", default-features = false }
rlp = { version = "0.5", default-features = false }
scale-info = { version = "2.1.2", default-features = false, features = [ "derive" ] }

# Substrate
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-timestamp = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# Frontier
fp-ethereum = { workspace = true }
fp-evm = { workspace = true }
fp-rpc = { workspace = true }
fp-self-contained = { workspace = true }
pallet-evm = { workspace = true }
xcm-primitives = { path = "../../primitives/xcm/", default-features = false }

[dev-dependencies]
pallet-ethereum = { workspace = true }
pallet-evm = { workspace = true }
pallet-proxy = { workspace = true }

hex = "0.4.3"
# Parity
libsecp256k1 = { version = "0.7", features = [ "hmac", "static-context" ] }
# Substrate FRAME
pallet-balances = { workspace = true, version = "4.0.0-dev" }
# Substrate
sp-core = { workspace = true, version = "6.0.0" }

[features]
default = [ "std" ]
std = [
	# Parity
	"codec/std",
	"ethereum-types/std",
	"ethereum/std",
	# Frontier
	"fp-ethereum/std",
	"fp-evm/std",
	"fp-rpc/std",
	"fp-self-contained/std",
	# Substrate FRAME
	"frame-support/std",
	"frame-system/std",
	"pallet-evm/std",
	"pallet-timestamp/std",
	"rlp/std",
	"scale-info/std",
	"serde",
	# Substrate
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm-primitives/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-evm/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
]
try-runtime = [ "frame-support/try-runtime" ]
